server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: user_service
            uri: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8081}
            predicates:
              - Path=/api/users/**, /api/auth/**, /users/swagger-ui/**, /users/api-docs/**

          - id: payment_service
            uri: http://${PAYMENT_SERVICE_HOST:localhost}:${PAYMENT_SERVICE_PORT:8082}
            predicates:
              - Path=/api/payments/**, /payments/swagger-ui/**, /payments/api-docs/**

          - id: event_service
            uri: http://${EVENT_SERVICE_HOST:localhost}:${EVENT_SERVICE_PORT:8083}
            predicates:
              - Path=/api/events/**, /events/swagger-ui/**, /events/api-docs/**

          - id: venue_service
            uri: http://${VENUE_SERVICE_HOST:localhost}:${VENUE_SERVICE_PORT:8084}
            predicates:
              - Path=/api/venues/**, /api/reservations/**, /venues/swagger-ui/**, /venues/api-docs/**

          - id: guest_service
            uri: http://${GUEST_SERVICE_HOST:localhost}:${GUEST_SERVICE_PORT:8085}
            predicates:
              - Path=/api/guests/**, /guests/swagger-ui/**, /guests/api-docs/**

          - id: notification_service
            uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8086}
            predicates:
              - Path=/api/notifications/**, /notifications/swagger-ui/**, /notifications/api-docs/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
        security:
          web: DEBUG
