server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: user_service
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**, /api/auth/**

          - id: payment_service
            uri: http://localhost:8082
            predicates:
              - Path=/api/payments/**

          - id: event_service
            uri: http://localhost:8083
            predicates:
              - Path=/api/events/**

          - id: venue_service
            uri: http://localhost:8084
            predicates:
              - Path=/api/venues/**

          - id: guest_service
            uri: http://localhost:8085
            predicates:
              - Path=/api/guests/**

          - id: notification_service
            uri: http://localhost:8086
            predicates:
              - Path=/api/notifications/**

          - id: user_swagger_ui
            uri: http://localhost:8081
            predicates:
              - Path=/users/swagger-ui/**, /users/api-docs/**

          - id: payment_swagger_ui
            uri: http://localhost:8082
            predicates:
              - Path=/payments/swagger-ui/**, /payments/api-docs/**

          - id: event_swagger_ui
            uri: http://localhost:8083
            predicates:
              - Path=/events/swagger-ui/**, /events/api-docs/**

          - id: venue_swagger_ui
            uri: http://localhost:8084
            predicates:
              - Path=/venues/swagger-ui/**, /venues/api-docs/**

          - id: guest_swagger_ui
            uri: http://localhost:8085
            predicates:
              - Path=/guests/swagger-ui/**, /guests/api-docs/**

          - id: notification_swagger_ui
            uri: http://localhost:8086
            predicates:
              - Path=/notifications/swagger-ui/**, /notifications/api-docs/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
        security:
          web: DEBUG
